### ISSUE TITLE
doesn't "work" [quickstart]

### ISSUE THREAD

**Issue by adityanatraj** [dewittn/hugo-html5up-alpha#1]
I followed the hugo quick-start instructions with version:
```
Hugo Static Site Generator v0.72.0-8A7EF3CF linux/amd64 BuildDate: 2020-05-31T12:07:45Z
```
creating a new empty site, and cloning this into a submodule (themes/alpha). 

After adding the `theme = "alpha"` line to the config.yaml and running
```
hugo server -D
```

this is the failure output:
```
[ 1078 ] user:site % hugo server -D
Built in 28 ms
Error: Error building site: TOCSS: failed to transform "main.scss" (text/x-scss): resource "scss/sass/main.scss_e95820d474fe7cf9c38afe1151187c97" not found in file cache
```

I'm not sure if I've done something wrong because there aren't any more steps or details to follow. Are there undocumented scss compilation steps?

It's a beautiful theme; just wondering how I can get it to work...

thanks.

**Comment by dewittn** [comment]
Hi @adityanatraj,

I don't believe there are any SCSS complications. 

Are you running `hugo server -D` with an empty Hugo project? 

If so, that might be the problem. This theme won't run out of the box without a bit of configuration.

1. Copy [the config.toml file](https://github.com/dewittn/hugo-html5up-alpha/blob/master/exampleSite/config.toml) from `exampleSite` directory and replace the contents of your config.toml file.
2. Copy the`exampleSite\data' directory to your project's base directory.
3. Optionally, you can copy the files in the `exampleSite\content' directory into your project's `content` directory.

From there you can modify the contents and settings as you see fit. Let me know if that fixes your problem.

I'll try to make this process clearer in the `README.md` file

**Comment by ryanerwin** [comment]
This theme actually requires the `hugo-extended` package rather than the default hugo package.
> you may install the “extended” Sass/SCSS version

```
# windows
scoop install hugo-extended
#-or-
choco install hugo-extended -confirm
# linux
snap install hugo --channel=extended
```

See https://gohugo.io/getting-started/installing/ and note "extended"

**Comment by dewittn** [comment]
@ryanerwin Thanks for that note. I'm running the default Brew version, which must include the extended packages by default. I'll add that info into the readme next time I update.
