### ISSUE TITLE
Errors using this theme with R's Blogdown

### ISSUE THREAD

**Issue by ixodid198** [dewittn/hugo-html5up-alpha#2]
Trying to use this theme with R, RStudio and Blogdown as per [here](https://bookdown.org/yihui/blogdown/workflow.html)

Other themes install OK in my current configuration.

blogdown::new_site(theme = 'dewittn/hugo-html5up-alpha')
trying URL 'https://github.com/dewittn/hugo-html5up-alpha/archive/master.tar.gz'
downloaded 2.7 MB

The latest Hugo version is 0.74.3
trying URL 'https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_macOS-64bit.tar.gz'
Content type 'application/octet-stream' length 15971844 bytes (15.2 MB)
==================================================
downloaded 15.2 MB

Hugo has been installed to /Users/law/Library/Application Support/Hugo
Error: "/Users/law/R/test_hugo_theme2/themes/hugo-html5up-alpha/layouts/partials/bannerURL.html:7:1": parse failed: template: partials/bannerURL.html:7: function "return" not defined
Warning: You are recommended to ignore certain files in config.toml: set the option ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
Rendering content/blog/2015-07-23-r-rmarkdown.Rmd
Error: "/Users/law/R/test_hugo_theme2/themes/hugo-html5up-alpha/layouts/partials/bannerURL.html:7:1": parse failed: template: partials/bannerURL.html:7: function "return" not defined
To stop the server, run servr::daemon_stop(1) or restart your R session
Serving the directory /Users/law/R/test_hugo_theme2 at http://127.0.0.1:4321
Warning message:
In file.copy(exec, destdir, overwrite = TRUE) :
  problem copying ./hugo to /usr/local/bin/hugo: Permission denied

**Comment by dewittn** [comment]
@ixodid198 I have not used Rstudio, so I don't if I can be of much help. However, based on the error message, there seems to be a problem with the `return` function. This could be an error caused by a the relaese of Hugo 74, which I have not tested with my theme.

I'll look into fixing this error, but in the meantime, you could try using the theme with Hugo version .70.

**Comment by dewittn** [comment]
@ixodid198 I tested the theme with Hugo 0.74.3 this morning and the theme worked for me. It could be a problem with the way Rstudio installs it or maybe you are running the theme with an empty `config.toml` file. Try copying `config.toml` from `\examptleSite` into your project. Other than that, I'm afraid I can't be of much help. Good luck!

**Comment by ixodid198** [comment]
OK. Thank-you for looking into this.
